language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer require satooshi/php-coveralls

install:
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --verbose

after_script:
  - php vendor/bin/coveralls -v